# Generated by Django 5.2.13 on 2026-04-16 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='courses_cou_price_1fbd18_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'price'], name='courses_cou_teacher_b6d268_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemember',
            index=models.Index(fields=['course_id', 'roles'], name='courses_cou_course__1917cf_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemember',
            index=models.Index(fields=['user_id'], name='courses_cou_user_id_1be9bf_idx'),
        ),
    ]
